### ISSUE TITLE
Expose SQLite config

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#104]
The current config silences SQLite because it's verbose.

```ts
self.sqlite3ApiConfig = {
  debug: constVoid,
  log: constVoid,
  warn: constVoid,
  error: constVoid,
};
```

**Comment by michalvavra** [comment]
How can I replicate verbose logs?

Removing `self.sqlite3ApiConfig` doesn't show me any (tested with Chrome v110 and v112).

**Comment by steida** [comment]
Check https://sqlite.org/wasm/doc/trunk/index.md or the source code itself.

**Comment by steida** [comment]
I think it's not necessary.
