### ISSUE TITLE
Example app crashes on iOS safari

### ISSUE THREAD

**Issue by bashlk** [evoluhq/evolu#106]
Really interested in evolu so was trying out the example app on Safari on Mac and iPhone. Works fine on Safari on Mac but crashes on iOS safari (iPhone 8 - iOS 15.1)

Here is a screenshot of the crash - probably mobile Safari does not support one of the browser APIs used by evolu.
![IMG_0902](https://user-images.githubusercontent.com/11556301/220612352-e0c9d56a-b88f-44e7-bb96-224b991a000e.PNG)

The underlying question I was trying to figure out is whether evolu can synchronise data when one of the peers is offline. Does the server store a complete copy of the data or does it delete the data once it has been relayed to the other device?

**Comment by steida** [comment]
Thank you for the report. I didn't test iOS < 16, to be honest. It probably fails because of the Lock API. Evolu uses Lock API `navigator.locks` to ensure only one sync is processed across tabs. It's available from Safari 15.4. I think we can use polyfill https://github.com/aermin/web-locks.

**Comment by steida** [comment]
> The underlying question I was trying to figure out is whether evolu can synchronise data when one of the peers is offline. Does the server store a complete copy of the data or does it delete the data once it has been relayed to the other device?

Server store a complete copy of the data.
