### ISSUE TITLE
Safari OPFS

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#135]
There were a few blockers. Safari TP already supports nested workers, and maybe this: https://bugs.webkit.org/show_bug.cgi?id=250495

Retest when Safari 16.4 will be out.

**Comment by gigq** [comment]
This would support 256MB in Safari then? Nice.

**Comment by steida** [comment]
@gigq Stephan from the SQLite team told me that. But maybe it's not relevant anymore. I plan to do some stress tests.

**Comment by steida** [comment]
Done!
