### ISSUE TITLE
Is the documentation outdated?

### ISSUE THREAD

**Issue by iamwilhelm** [evoluhq/evolu#142]
The guide says to use `Infer`, but it doesn't exist in the codebase, and the sample nextjs app doesn't use it at all.

**Comment by steida** [comment]
Docs will be updated soon. It's just different naming.

**Comment by steida** [comment]
I'm migrating Evolu from fp-ts to Effect, and it will be completed soon.

**Comment by steida** [comment]
Done. Docs are actual.
