### ISSUE TITLE
Ability to set database name

### ISSUE THREAD

**Issue by mifozski** [evoluhq/evolu#149]
Evolu should expose the ability to define a database filename that will be created on OPFS so the users can have multiple databases on the same origin (for example, for multi-account usage).
The database filename should be passed as a param to the `createHooks` method in the `Config` object.

**Comment by steida** [comment]
@mifozski I agree. The problem is that LocalStorage used where OPFS is unavailable, does not support multiple databases.

> This VFS supports only a single database per storage object. That is, there can be, at most, one localStorage database and one sessionStorage database. 

https://sqlite.org/wasm/doc/trunk/persistence.md

The affected browser is Safari. A bug blocking OPFS is already fixed, but it will take time to be available for all.

If you have an idea how to solve it, feel free to help 🙂

**Comment by mifozski** [comment]
@steida  My idea was to just focus on the support for the OPFS storage, and I think we can decide that it's not going to be supported with localStorage, and Safari has its own limitation that are unrelated to this change.
But overall, I was planning to help with the PR for the OPFS support.

**Comment by steida** [comment]
@mifozski Evolu already supports OPFS where available.

**Comment by steida** [comment]
OPFS for Safari is already implemented in Evolu, so I suppose we can wait a few months for Safari 17 to be adopted, and then drop LocalStorage entirely. Then we can add support for more databases.

**Comment by negue** [comment]
> hey i actually implemented this

Nice!, do you have a snippet of how you did that?

Looking at https://github.com/evoluhq/evolu/issues/309 I think we'll have an official feature soon ™️  🎉

**Comment by steida** [comment]
So how should the Evolu "multitenancy" work? What are the use cases? 🤔

The first use case is dev on localhost, where each app would be isolated from others. That would be nice.
For that use case, the config can accept the optional name.

The second use case is the ability to have more Evolu instances run concurrently and even dynamically 🤔
That's perfectly possible, but I must rework Evolu internals first.

**Comment by danilaplee** [comment]
i will provide an MR next week

**Comment by negue** [comment]
> closed this as completed

ohh awesome!!

**Comment by steida** [comment]
@negue It doesn't mean that more Evolu instances can be used concurrently. It will be possible, but not yet.

**Comment by negue** [comment]
I for one only needed a different database name so far - I wont have two apps / evolu instances in the same browser tab :)

The other multiple instances feature I'll probably use as well but not a missing feature for me (yet)
