### ISSUE TITLE
Access to fetch at 'https://evolu.world/' from origin 'http://localhost:3000' has been blocked by CORS policy

### ISSUE THREAD

**Issue by FilipChalupa** [evoluhq/evolu#168]
> Access to fetch at 'https://evolu.world/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![image](https://github.com/evoluhq/evolu/assets/1045362/fa71060b-3a1f-44fb-b6b7-408e330b5af6)

Synchronization with `https://evolu.world` fails. To reproduce this issue comment out line 51 to 53 in `NextJsExample.tsx`.

**Comment by steida** [comment]
@FilipChalupa All I can say is that it works for me with MacOS. Maybe it's something specific to Ubuntu?

**Comment by steida** [comment]
It was something not related to Evolu, I think. Feel free to reopen this issue.
