### ISSUE TITLE
Public data with an owner?

### ISSUE THREAD

**Issue by ondrej-langr** [evoluhq/evolu#179]
Hey, 
Love the direction this is rolling. I was tinkering with this for some time and I was wondering how would you set public data with an owner? I only found out that all data are encrypted and not publicly sharable to other users (technically users can sync with your server, but thats about it - atleast to my knowledge)

Typical scenarion would be platform like Twitter. User writes a "post" and wants engagement on their "post" - aka likes, comments, etc... Another scenario could be messaging app.

Is this something that its possible ATM? If not then would it be even supported? (you kind of can achieve this with gun.js)

Thanks 🫶

**Comment by steida** [comment]
I think sharing data with other people and sharing data publicly are two different use cases than owning data, and therefore different means are required. For sharing among a few members, there is public/private cryptography. For public data, there are endless other options.
