### ISSUE TITLE
Export DB file

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#184]
```ts
/** Export SQLite database as Uint8Array. */
readonly exportDatabase: () => Effect.Effect<Uint8Array>;
```

`const byteArray = sqlite3.capi.sqlite3_js_db_export(myDb);`
`db.serializeAsync`

**Comment by danilaplee** [comment]
and also implemented this

**Comment by steida** [comment]
@danilaplee I will take a look at your code, thank you!

**Comment by steida** [comment]
@danilaplee, Would you like to help me with that feature?

**Comment by steida** [comment]
Done
