### ISSUE TITLE
Error when using Evolu with Vite 

### ISSUE THREAD

**Issue by kaladivo** [evoluhq/evolu#254]
I am trying to use Evolu with Vite and I am getting the following errors: 

- In dev server: loading dep (outdated optimize dep) when loading `DbWorker.worker.js`
- When trying to build:  `Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.`

You can replicate the error here (just run `npm run dev` / `npm run build` in the repo): 
https://github.com/kaladivo/evolu-vite-error

**Comment by steida** [comment]
Hi, thank you for the report. I planned to add a Vite example anyway, so I will fix it soon.

**Comment by steida** [comment]
Done.

https://github.com/evoluhq/evolu/tree/main/examples/vite

**Comment by steida** [comment]
Not yet. Only the dev is working. The build still has to be fixed.

**Comment by steida** [comment]
Related https://github.com/evoluhq/evolu/issues/262
