### ISSUE TITLE
Type errors with `@effect/schema/Schema`

### ISSUE THREAD

**Issue by vadimyen** [evoluhq/evolu#259]
I created a new project with Vite React + TypeScript template. After running, `pnpm install`, I copy-pasted the code from [this example](https://www.evolu.dev/docs/guide#define-data):
```ts
import * as Evolu from "@evolu/react";
import * as Schema from "@effect/schema/Schema";

const TodoId = Evolu.id("Todo");
type TodoId = Schema.Schema.To<typeof TodoId>;

const TodoTable = Schema.struct({
  id: TodoId,
  title: Evolu.NonEmptyString1000,
  isCompleted: Evolu.SqliteBoolean,
});
type TodoTable = Schema.Schema.To<typeof TodoTable>;

const Database = Schema.struct({
  todo: TodoTable,
});

export const {
  useQuery,
  useMutation,
  useOwner,
  useOwnerActions,
  useEvoluError,
} = Evolu.create(Database);
```
But I got this error `TS2307: Cannot find module @effect/schema/Schema or its corresponding type declarations.` in the line `import * as Schema from "@effect/schema/Schema";` 

I tried to install the `@effect/schema` manually, but after that I got another error:
```
TS2344: Type
BrandSchema<string, string & Brand<"Id"> & Brand<"Todo">>
does not satisfy the constraint
{   readonly [TypeId]: {     readonly To: (..._: any) => any;   }; }
Property  [TypeId]  is missing in type
BrandSchema<string, string & Brand<"Id"> & Brand<"Todo">>
but required in type
{   readonly [TypeId]: {     readonly To: (..._: any) => any;   }; }
Schema.d.ts(59, 18):  [TypeId]  is declared here.
```
![image](https://github.com/evoluhq/evolu/assets/22547943/b2e3a228-4579-4c9d-95bc-a9d9e60dc84a)

How can I fix it? I might miss that bit, but where does the lib declare `@effect/schema` dependency and its version?

**Comment by steida** [comment]
Evolu's new API is done (I'm writing docs for that), and this will be the first issue I will take a look at.

**Comment by vadimyen** [comment]
Good, thanks

**Comment by steida** [comment]
PNPM for some reason doesn't install peer dependencies. I will update the docs.

**Comment by steida** [comment]
Also, I'm working on the Vite Evolu example right now.
