### ISSUE TITLE
Add a way to sychronize imperatively and/or disable syncing on focus/reconnect

### ISSUE THREAD

**Issue by arekmaz** [evoluhq/evolu#275]
in order to enable a wider range of app types I think manipulating the moment of sync / disabling the default ones would be valuable

e.g. a "sync now" button, or real-time updates

this would be I guess enabled by exposing the dbWorker to be able to postMessage arbitrarily,

or exposing a sync function from one of the packages

**Comment by steida** [comment]
What's wrong with a sync invoked on a mutation? I can expose API for that, but please help me to understand the use case.

I can provide API for temporally disabled syncing, but Evolu already has a concept of local-only tables (a table with the _ prefix in the name). They are not synced. When developers decide the data should be synced, they move it to regular Evolu tables.

For manual syncing, Evolu can expose a sync function for that:

`dbWorker.postMessage({ _tag: "sync", queries: getSubscribedQueries() });`
and
`dbWorker.postMessage({ _tag: "sync", queries: [] });`

**Comment by arekmaz** [comment]
I'm not sure about the disabling of the defaults, but I'm sure the imperative sync will be very useful

**Comment by steida** [comment]
Done
