### ISSUE TITLE
COEP and COOP required headers conflict with 3rd party scripts, such as payment gateways

### ISSUE THREAD

**Issue by jericopulvera** [evoluhq/evolu#309]
As mentioned by @steida, "those headers are required by the official SQLite WASM library. The only possible solution is to use an alternative unofficial SQLite WASM, this one: https://github.com/rhashimoto/wa-sqlite. It's not something Evolu supports out of the box, but we can add it if someone really needs it."

It would be great if we could have an option to use wa-sqlite instead of the official SQLite WASM library.

**Comment by steida** [comment]
If you need this feature ASAP, feel free to send PR. It should be relatively easy. The hardest issue to figure out is how `@evolu/common-web` and `@evolu/react` should be configured.

**Comment by rhashimoto** [comment]
The official SQLite WASM added support for another OPFS virtual file system, [opfs-sahpool](https://sqlite.org/wasm/doc/trunk/persistence.md#vfs-opfs-sahpool). This VFS has its own limitations - in particular it doesn't support multiple connections to the database - but it doesn't require COOP/COEP and once the database is open it provides the identical API. It's apparently also [significantly faster](https://sqlite.org/forum/forumpost/1d767118bc077703).

If you can live with a single database connection then that might be an easier modification than changing SQLite WASM implementations.

**Comment by steida** [comment]
@rhashimoto Hi! Thank you for the comment. I admire your work.

I thought about opfs-sahpool, but Evolu really needs to support multiple tabs, so we have to build a robust API around Web Locks and other APIs first. As you demonstrated, it's doable. I plan to do it once I solve other currently more important Evolu issues.

**Comment by rhashimoto** [comment]
@steida Using a SharedWorker is fairly straightforward. I don't think I would call sharing a dedicated Worker straightforward, but it can be made to work.

I don't think SharedWorker is coming to Android anytime soon. The [chromium bug](https://issues.chromium.org/issues/40290702) has been around for 10+ years with no developer comment since 2021. It also doesn't show up as a goal for [Interop 2024](https://web.dev/blog/interop-2024) - maybe we should try to get that on the list for Interop 2025 when the call goes out later this year.

**Comment by steida** [comment]
> At the time there was a reasonable reason (complexity and implementation costs vs. lack of strong use cases / partners).
Things are a bit different these days. That said, there are other interop requests that compete for the team's bandwidth, beside their main projects. The other requests have clearer signals of impact at the moment.
What is the reason SharedWorker should be desktop-only when every other browser is able to ship it on mobile?
To be clear, no one said that SharedWorker should be desktop-only.
This is not an if, it's a when.

https://groups.google.com/a/chromium.org/g/blink-dev/c/H73tticuudc/m/NunrjwcBBwAJ

**Comment by steida** [comment]
It's tempting to spend days, maybe weeks, with Leader election https://rxdb.info/leader-election.html, but other Evolu features are waiting to be implemented. Let's assume mobile users will not open more tabs, and if so, we can detect it.

**Comment by steida** [comment]
"The disadvantage is that the leader election process takes some time on the initial page load (about 150 milliseconds). Also the leader election can break when a JavaScript process is fully blocked for a longer time. When this happens, a good way is to just reload the browser tab to restart the election process."

https://rxdb.info/slow-indexeddb.html#in-memory-multi-tab-support

**Comment by steida** [comment]
Reliable leader election is hard: https://github.com/okikio/sharedworker/issues/1#issuecomment-1719108203

**Comment by steida** [comment]
So, I solved it with Web Locks and BroadcastChannel only. It's probably not as efficient as dedicated broadcast channels, but it's simple and works everywhere.

**Comment by steida** [comment]
Done
