### ISSUE TITLE
expo-sqlite/next

### ISSUE THREAD

**Issue by abdelhameedhamdy** [evoluhq/evolu#317]
Hey there, 

Any plans to support the new v13.x [expo-sqlite/next](https://docs.expo.dev/versions/v50.0.0/sdk/sqlite-next/) !

Thanks

**Comment by steida** [comment]
@abdelhameedhamdy If you have time, feel free to send a PR with an update for expo-sqlite/next, it should be easy.

**Comment by steida** [comment]
Done.
