### ISSUE TITLE
Add Kysely db.with() to the allowed Methods 

### ISSUE THREAD

**Issue by negue** [evoluhq/evolu#348]
I wanted to try using a Recursive Call (based on that example https://stackoverflow.com/a/71872392) but I found that the Interface of Kysely was only exporting two methods:

```
type QueryCallback<S extends DatabaseSchema, R extends Row> = (
  db: Pick<Kysely.Kysely<QuerySchema<S>>, "selectFrom" | "fn">,
) => Kysely.SelectQueryBuilder<any, any, R>;
```

I would like to add [`.with`](https://kysely-org.github.io/kysely-apidoc/classes/Kysely.html#with) (in a PR) to this Pick<>'ed Arguments, 

Question is, would that all that is needed to change or does it have a bit more dependencies to get this running 😬

**Comment by steida** [comment]
It should be enough. Run Evolu dev, remove that pick, and get the whole Kysely. The reason why Evolu picks only selected props is to hide mutation API. Mutation must be done differently, but we can use everything Kysely provides for queries.

**Comment by negue** [comment]
Using 

```ts
type QueryCallback<S extends DatabaseSchema, R extends Row> = (
  db: Pick<
    Kysely.Kysely<QuerySchema<S>>,
    "selectFrom" | "fn" | "with" | "withRecursive"
  >,
) => Kysely.SelectQueryBuilder<any, any, R>;
```

resulted in zero errors (running pnpm dev on the root folder) - so that seems to be working

but weirdly when I tried to extract the Picked Type to its own like this:

```ts
type KyselyAllowedMethods<S extends DatabaseSchema> = Pick<
  Kysely.Kysely<QuerySchema<S>>,
  "selectFrom" | "fn" | "with" | "withRecursive"
>;

type QueryCallback<S extends DatabaseSchema, R extends Row> = (
  db: KyselyAllowedMethods<S>,
) => Kysely.SelectQueryBuilder<any, any, R>;
```

it resulted in:

```
@evolu/common:dev: src/Evolu.ts:834:12 - error TS2352: Conversion of type 'Evolu<DatabaseSchema>' to type 'Evolu<To>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@evolu/common:dev:   Types of property 'createQuery' are incompatible.
@evolu/common:dev:     Type 'CreateQuery<DatabaseSchema>' is not comparable to type 'CreateQuery<To>'.
@evolu/common:dev:       Types of parameters 'queryCallback' and 'queryCallback' are incompatible.
@evolu/common:dev:         Types of parameters 'db' and 'db' are incompatible.
@evolu/common:dev:           Type 'KyselyAllowedMethods<DatabaseSchema>' is not comparable to type 'KyselyAllowedMethods<To>'.
@evolu/common:dev:             The types returned by 'selectFrom(...).where(...).innerJoin(...)' are incompatible between these types.
@evolu/common:dev:               Type 'SelectQueryBuilder<{ [x: string]: NullableExceptId<{ readonly [x: string]: Value; readonly id: string & Brand<"Id">; }>; }, any, {}> | SelectQueryBuilder<...>' is not comparable to type '(string extends keyof DrainOuterGeneric<{ [C in string | keyof To | (any extends keyof To ? any : never)]: C extends string | (any extends keyof To ? any : never) ? (string extends C ? string extends keyof To ? QuerySchema<...>[keyof To & string] : never : never) | (any extends C ? any extends keyof To ? QuerySchema...'.
@evolu/common:dev:                 Type 'SelectQueryBuilder<{ [x: string]: NullableExceptId<{ readonly [x: string]: Value; readonly id: string & Brand<"Id">; }>; }, any, {}>' is not comparable to type '(string extends keyof DrainOuterGeneric<{ [C in string | keyof To | (any extends keyof To ? any : never)]: C extends string | (any extends keyof To ? any : never) ? (string extends C ? string extends keyof To ? QuerySchema<...>[keyof To & string] : never : never) | (any extends C ? any extends keyof To ? QuerySchema...'.
@evolu/common:dev:                   Type 'SelectQueryBuilder<{ [x: string]: NullableExceptId<{ readonly [x: string]: Value; readonly id: string & Brand<"Id">; }>; }, any, {}>' is not comparable to type 'any extends keyof DrainOuterGeneric<{ [C in string | keyof To | (any extends keyof To ? any : never)]: C extends string | (any extends keyof To ? any : never) ? (string extends C ? string extends keyof To ? QuerySchema<...>[keyof To & string] : never : never) | (any extends C ? any extends keyof To ? QuerySchema<......'.
@evolu/common:dev: 
@evolu/common:dev: 834     return evolu as Evolu<To>;
@evolu/common:dev:                ~~~~~~~~~~~~~~~~~~
```

which is weird cause it just moved the inner Pick outside ... but oh well - atleast the first approach worked

**Comment by steida** [comment]
I will take a look once current PR will be completed.

**Comment by negue** [comment]
Will create the PR later today

**Comment by negue** [comment]
When trying out `.with` and `.withRecursive` I saw that both, the result of that Method and the internal builder exposed multiple mutation methods, which was quite a surprise to me. 

While digging in docs/issues of Kysely I found this: https://github.com/kysely-org/kysely/pull/218 - Sadly it seems to be quite stale - I don't think it would be possible to re-type everything from evolu's library side to get all Types of Kysely be ReadOnly 

The suggested idea of https://github.com/kysely-org/kysely/pull/218#issuecomment-1304500903 would only disable the top level methods (which here it is already done by `Pick<>` but also not the returns/callback builder so I don't think this should be added to the public api - yet

But I found a workaround that if someone needs more Kysely API they can re-type it in their Code itself

```ts
import {Kysely} from "kysely";

export const Database = database({
  todo: TodoTable
});

  const myDB = db as Kysely<Database>;
```

This could be added with a big warning of "DO NOT USE THE MUTATION METHODS OF THAT" or something like that haha, but atleast its a workaround until that PR might be merged

**Comment by steida** [comment]
We must detect mutation queries and throw an exception if someone uses mutation in SQL.

As for types, I'm afraid we will have to patch Kysely to reduce its size by removing unused mutation-related code anyway.
