### ISSUE TITLE
created entry is not found right after using getQuery

### ISSUE THREAD

**Issue by negue** [evoluhq/evolu#349]
Ran into an issue the last hour, if you create an entry and load it right after (just in my example, but in the actual case the time between those steps are a few seconds)

```js
const {id: parentEntryId} = evolu.create("todo", {
   title: S.decodeSync(NonEmptyString1000)("Entry 1"),
   isCompleted: false
});

    console.info({
      parentEntryId
    });
    
const query = evolu.createQuery(
  db => db.selectFrom("todo")
    .selectAll()
    .where("id", "==", parentEntryId)
);
   const result = evolu.getQuery(query);

   console.info(parentEntryId, query, result);
         // result.row is undefined
         // result.rows is []
```

using loadQuery worked here, so I don't know if its by design or if its a bug

Looking at the Docs of getQuery it is only with the subscribeQuery example, which means thats only meant to be called after (and inside) the SubscribeQuery is called ?

If so - maybe that getQuery could/should be moved into the callback argument? then no one else would fall into this obstacle ever again 😬

**Comment by steida** [comment]
If you look at the source code (click on the function), you will see that `getQuery` only returns rows from the store, nothing else. It's API for React https://react.dev/reference/react/useSyncExternalStore#usesyncexternalstore and similar APIs.

**Comment by steida** [comment]
I think the name is what confused you. It should be named `getQueryResult`. I will fix it.

**Comment by negue** [comment]
>  you will see that getQuery only returns rows from the store

So this store is only filled by the `subscribe` Methods? If so what do you think about adding such a comment or warning of "only use inside `subscribeX` ? => I could add that later in a PR^^

> It's on par with other subscribers

I didn't know that these are dependent, I thought one was a sync query the other a promise based

> It can't be within a callback. It must be separated

What I meant was something like this:

```js
const unsubscribe = evolu.subscribeQuery(allTodos)((subscribeContext) => {      
   const {rows} = subscribeContext.getQueryResult();    
  // still only executed when needed inside the subscribe-callback like currently the .getQuery is, 
  // just not a top-level api method
});
```

That way there would be only `loadQuery` and `subscribeQuery` and no `getQuery` which only works inside `subscribeQuery` to stumble over 😄

 > You shouldn't need that API if you use React.

Will write next time what Framework and what source (common-web) I use, I don't use React at all 😅 , currently trying it with Svelte :) and trying to report/ improve every obstacle I get as a new library user 😬

**Comment by steida** [comment]
API is OK. `subscribeQuery` means you are interested in knowing whether anything has been changed. If so, then you will read it with `getQuery`. There is a reason why it's defined as it's defined.
