### ISSUE TITLE
Hi I have built a collaborative video editor using evolu

### ISSUE THREAD

**Issue by danilaplee** [evoluhq/evolu#383]
You can check my app here
https://www.starpy.me/

**Comment by steida** [comment]
@danilaplee Wow! Will check as soon as I finish refactoring (no API changes, new features)

**Comment by steida** [comment]
@danilaplee May I add to https://www.evolu.dev/docs/showcase?

**Comment by steida** [comment]
Added to https://www.evolu.dev/docs/showcase

@danilaplee Thank you :-)
