### ISSUE TITLE
Allow swapping of Effect services

### ISSUE THREAD

**Issue by hmbrg** [evoluhq/evolu#386]
In some use cases, it might be helpful to swap out Effect services in order to, for example, use another database provider or another networking layer.

To achieve this, Evolu could allow replacing any internally used effect services via the `evlolu()` factory method.

I think this added functionality would benefit people in lots of use cases!

**Comment by steida** [comment]
That's already possible. Check how createEvolu functions are made. For example, in React Native:

```ts
export const EvoluFactoryReactNative = Layer.provide(
  EvoluFactory.Common,
  Layer.mergeAll(
    Layer.succeed(DbFactory, {
      createDb: createDb.pipe(
        Effect.provide(
          Layer.mergeAll(
            Bip39Live,
            SqliteFactory.Common.pipe(
              Layer.provide(SqliteFactoryLive),
              Layer.provide(NanoIdGeneratorLive),
            ),
            NanoIdGeneratorLive,
            Time.Live,
            SyncFactoryLive,
            SyncLockLive,
          ),
        ),
      ),
    }),
    NanoIdGeneratorLive,
    AppStateLive,
  ),
);
```
