### ISSUE TITLE
More explanation of how to delete rows in documentation

### ISSUE THREAD

**Issue by Renovamen** [evoluhq/evolu#396]
Hi, thank you so much for this project, I really enjoy using it. 

If I haven't overlooked anything, do you think it would be better to explicitly mention and explain that to delete a row from a table, we should just set `isDeleted` to `true` and that deletion only works for local-only tables? I don't have much knowledge about the sync mechanism, so I was a bit confused when I first read the documentation, even though it [implicitly mentions this](https://www.evolu.dev/docs/patterns#deferred-sync-with-local-only-tables). I had to look into the code to figure it out.

**Comment by steida** [comment]
Yeah, documentation could be better. May I ask you for PR?
