### ISSUE TITLE
NPM install does not work

### ISSUE THREAD

**Issue by jesper-bylund** [evoluhq/evolu#405]
From the [document install](https://www.evolu.dev/docs/installation)

```js
npm install @evolu/react
```

This results in the following error:

```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @evolu/common-web@8.0.3
npm WARN Found: @sqlite.org/sqlite-wasm@undefined
npm WARN node_modules/@sqlite.org/sqlite-wasm
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @sqlite.org/sqlite-wasm@"3.45.1-build2" from @evolu/common-web@8.0.3
npm WARN node_modules/@evolu/common-web
npm WARN   peer @evolu/common-web@"^8.0.2" from @evolu/react@8.0.2
npm WARN   node_modules/@evolu/react
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sqlite.org/sqlite-wasm@3.45.1-build2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Package does indeed not exist:
https://www.npmjs.com/package/@sqlite.org/sqlite-wasm?activeTab=versions

Should probably be `[3.45.2-build1](https://www.npmjs.com/package/@sqlite.org/sqlite-wasm/v/3.45.2-build1)` instead. I can't start the project so I'm wary of making a PR 😅

**Comment by jesper-bylund** [comment]
Turns out the evolu/common-web package as a peerDependecy of `3.45.1-build2` it should probably be `3.45.3-build2`

**Comment by steida** [comment]
@jesper-bylund Thank you for the report! I will fix it asap.

**Comment by steida** [comment]
@jesper-bylund A caret was missing, and https://github.com/QuiiBz/sherif didn't check it.

**Comment by jesper-bylund** [comment]
Super quick! Thanks! 🙏
