### ISSUE TITLE
Exclude modules containing relative worker paths from Vite dep optimization

### ISSUE THREAD

**Issue by piktur** [evoluhq/evolu#407]
Do not pre-bundle `@evolu/common-web`. Why? Worker relative import path resolution fails on registration because `@evolu/common-web/dist/*.worker.js` is not present in Vite's pre-bundled dependencies cache (typically `node_modules/.vite/deps`). 

True for any UI integration utilizing `@evolu/common-web`.

**Comment by steida** [comment]
Thank you for PR!
