### ISSUE TITLE
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: @changesets/assemble-release-plan@6.0.0

### ISSUE THREAD

**Issue by sectore** [evoluhq/evolu#421]
After merging latest `main` into #376 I got following error.

```bash
pnpm i
Scope: all 14 workspace projects
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: @changesets/assemble-release-plan@6.0.0

Either remove them from "patchedDependencies" or update them to match packages in your dependencies.
Progress: resolved 1810, reused 0, downloaded 0, added 0
```

Did run `pnpm clean` before.

Version check:
```bash
pnpm --version
9.1.3

node --version
v18.20.2
```

`patchedDependencies` was introduced in https://github.com/evoluhq/evolu/commit/79a6d0c69c5b18355ea43c81389fdd8cbfbb6524#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 What was the goal to have `patchedDependencies`?

**Comment by steida** [comment]
Changeset was updated, ok, I will fix it

**Comment by sectore** [comment]
> Changeset was updated, ok, I will fix it

In other case check #423
