### ISSUE TITLE
Unable to get vite based examples working

### ISSUE THREAD

**Issue by ibb2** [evoluhq/evolu#442]
Hi, I have been having issues with trying to implement this project with solid js, so I decided to try running the example to try and figure out what the problems could be. I have been trying to get the Vite and Vite+PWA examples running however have been unable too. The next js example work flawlessly. I have made sure to take out the folders from repo and have tried install with both npm and pnpm however, no dice, i keep getting a blank page and the following error `SyntaxError: The requested module '/node_modules/.pnpm/path-browserify@1.0.1/node_modules/path-browserify/index.js?v=3a13e745' does not provide an export named 'default' (at path.js?v=3a13e745:5:8)`. 
For Vite PWA the error is: `SyntaxError: The requested module '/node_modules/.pnpm/path-browserify@1.0.1/node_modules/path-browserify/index.js?v=ce82434b' does not provide an export named 'default' (at path.js?v=ce82434b:5:8)`. I have tried pinning version 0.68.11 for `@effects/schema` as suggested in the discord however that does not work either.

I have also noticed it seems that the standard vite example comes with the `@effect/schema` and `effect` packages missing so it will not run on just a default clone and install.

I am unsure if the issues are on my end. Or if there are current compatibility issues with Vite and effect/evolu.

Github links for the test repos:
Vite: https://github.com/ibb2/evolu-vite-pnpm-repo/tree/main
Vite + PWA: https://github.com/ibb2/evolu-vite-pwa-pnpm-repo

**Comment by steida** [comment]
@ibb2 Hi, thank you for reporting that. I will take a look right now.

**Comment by ibb2** [comment]
I was able to get the vite working with the following changes to the package.json dependencies.

    "@effect/schema": "0.66.14",
    "@effect/platform": "0.52.2",
    "@evolu/common": "5.0.3",
    "@evolu/react": "8.0.1",
    "@evolu/common-react": "8.0.3",
    "@evolu/common-web": "8.0.1",
    "effect": "3.4.7",
    "react": "18.2.0",
    "react-dom": "18.2.0".
The following also partially works but throws a weird error, that is not really replicable but does not stop the example working. the file is in the file [output-error.txt](https://github.com/user-attachments/files/16101325/output-error.txt):

    "@effect/schema": "0.67.24",
    "@evolu/common": "5.0.3",
    "@evolu/react": "8.0.1",
    "@evolu/common-react": "8.0.3",
    "@evolu/common-web": "8.0.1",
    "effect": "3.4.7",
    "react": "18.2.0",
    "react-dom": "18.2.0"

This also works, however only after running the first package json listed, it will fail if the vite example is fresh. It also fails if evolu react is bumped to the latest version and or effect schema is 68.*:

    "@effect/schema": "0.67.24",
    "@evolu/react": "8.0.1",
    "effect": "3.4.7",
    "react": "18.2.0",
    "react-dom": "18.2.0"

Interesting. Hope some of that helps.

**Comment by steida** [comment]
All examples were working; there must be some breaking change elsewhere. I don't use Vite or Remix; hopefully, examples author will fix it soon. Otherwise, I will have to fix it 🥲

**Comment by ibb2** [comment]
Hopefully they can get to it soon.

**Comment by steida** [comment]
@ibb2 Please tell me, does plain Evolu Web work for you? Platform wrappers are thin, so there is not much logic. The only issues can be related to bundling because Evolu uses Web Workers (to prevent the main thread blocking).

**Comment by ibb2** [comment]
All update to date packages it works if I replace just the table from evolu/react with evolu/common.

**Comment by TheUltDev** [comment]
@ibb2 can confirm importing table:
```ts
import {table} from '@evolu/common';
```
instead of
```ts
import {table} from '@evolu/react-native';
```
fixes the vite bundle issue (using rn + vite for web)

**Comment by steida** [comment]
@TheUltDev Vite examples were updated.
