### ISSUE TITLE
Add SQLite Index to Evolu server

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#45]
https://www.sqlitetutorial.net/sqlite-index

**Comment by roadmonster** [comment]
Hi, I am interested in working on this. However, when I run npm install. Get these errors. Unsupported URL Type "workspace:": workspace:0.2.2. 222 

verbose stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:298:15)

Can you help with this? Thank you.

**Comment by steida** [comment]
Hi, thank you. I updated https://github.com/evoluhq/evolu#contributing. Evolu uses pnpm so you have to install it first.

**Comment by steida** [comment]
Done
