### ISSUE TITLE
use in already use project.

### ISSUE THREAD

**Issue by wogno** [evoluhq/evolu#471]
I have saas that already use by many people, i want to add offline mode on electron and react native app, so after read documentation, I don't see how to sync my host database with local database using evolu. 

So, I want to if it's possible, because actually I use rest and my own implementation of sync, that oblige me to make more test than code. 
Thanks

**Comment by steida** [comment]
There is no plan now to make auto-sync with Postgres DB. Sorry, I can't help more.
