### ISSUE TITLE
Db.worker not found

### ISSUE THREAD

**Issue by karesztrk** [evoluhq/evolu#500]
Hey.

I'm trying to make Evolu working a simple Todo application.
But it fails when I create the database.
Do you have any hint?

![image](https://github.com/user-attachments/assets/232f58d5-cffc-498c-ab2f-bb428d3ecd33)

**Comment by needim** [comment]
Hi, can you share a reproduction?

It is hard to evaluate via screenshot.

**Comment by karesztrk** [comment]
Hey @needim. Sure thing.
```ts
import { Either } from 'effect';
import * as S from '@effect/schema/Schema';
import { NonEmptyString1000, SqliteBoolean, cast, database, id, table } from '@evolu/common';
import { createEvolu } from '@evolu/common-web';

const TodoId = id('Todo');

const TodoTable = table({
id: TodoId,
text: NonEmptyString1000,
done: S.NullOr(SqliteBoolean)
});

const Database = database({
todo: TodoTable
});

const evolu = createEvolu(Database);

const allTodos = evolu.createQuery((db) =>
db
	.selectFrom('todo')
	.selectAll()
	// SQLite doesn't support the boolean type, but we have `cast` helper.
	.where('done', 'is not', cast(true))
	.orderBy('createdAt')
);

// not called
evolu.loadQuery(allTodos).then((a) => console.log(a));
```

```json
{
   "dependencies": {
      "@effect/schema": "^0.75.5",
      "@evolu/common": "^5.4.8",
      "@evolu/common-web": "^8.2.4",
      "effect": "3.10.4"
   }
}
```

**Comment by needim** [comment]
Is it possible for you to create a github repository? So I can fork and test. Also you can check vite examples in here: https://github.com/evoluhq/evolu/tree/main/examples

**Comment by karesztrk** [comment]
@needim I've copied most of the stuff from there. I uploaded all of my work into this branch: https://github.com/karesztrk/todos/tree/evolu

**Comment by negue** [comment]
Maybe this option is missing from the vite.config.ts (haven't tried your repo yet, but I had some alike issues as well with getting the examples ready)

``` 
 optimizeDeps: {
    // A workaround for Vite bug: https://github.com/vitejs/vite/issues/13314#issuecomment-1560745780
    exclude: ["@evolu/common-web"],
  },
```


maybe also

```
 preview: {
    headers: {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "require-corp",
    },
  },
``` 

to get the SQLite in OPFS working

**Comment by karesztrk** [comment]
@negue. The `optimizeDeps` did the job. Thanks; it's working now. I think it should be emphasized more. I haven't seen it in the docs.

**Comment by steida** [comment]
Thank you, guys, for your help.

**Comment by harrywebdev** [comment]
if anyone struggles with this issue again, the mentioned fix has changed to

```
optimizeDeps: {
  exclude: ['@evolu/web']
},
```

in your `vite.config.ts`

---

for the record, I've noticed by this error in CLI (another symptom of the 404 in the browser)
> The file does not exist at "/Users/.../dev/project/node_modules/.vite/deps/Db.worker.js?worker_file&type=module" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.

**Comment by danilaplee** [comment]
i have same problem when compiling for react-native-web

<img width="921" height="371" alt="Image" src="https://github.com/user-attachments/assets/1a7ff006-dc8b-4908-b425-0aef0fd5181b" />

**Comment by steida** [comment]
hmm, that's probably because how react-native-web is compiled
