### ISSUE TITLE
Time travelling

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#57]
The API for rows history.

**Comment by hmbrg** [comment]
I'm highly interested in this feature! Are there any updates on this or any way to implement it myself?

**Comment by steida** [comment]
@hmbrg I started to implement it today. You can already read history values with the current API but without type hints.

```ts
const foo = (id: TodoId) => evolu.createQuery((db) =>
  db
    .selectFrom("evolu_message")
    .select("value")
    .where("table", "==", "todo")
    .where("row", "==", id),
);
```

I'm trying to figure out API and type magic for that.

**Comment by steida** [comment]
Hmm, type safety isn't trivial. We would have to make a view per table with conditional aggregation:

```sql
CREATE VIEW todo_history AS
SELECT
    timestamp,
    row,
    MAX(CASE WHEN column = 'title' THEN value END) AS title,
    MAX(CASE WHEN column = 'isCompleted' THEN value END) AS isCompleted
FROM
    evolu_message
WHERE
    "table" = 'todo'
GROUP BY
    timestamp, row
ORDER BY
    timestamp DESC;
```

The query would be nice:

```sql
SELECT
    timestamp,
    title,
    isCompleted
FROM
    todo_history
WHERE
    row = 'EIcGfm1Av0UFBrFd_bx69';
```

But output not:

<img width="490" alt="Screenshot 2024-05-07 at 19 54 03" src="https://github.com/evoluhq/evolu/assets/66249/5cdf8b87-7c50-44e5-87d3-d2e4ef5c637b">

**Comment by steida** [comment]
OK. We don't need type safety here because Evolu Schema is append-only, so it will never be refactored.
All we need is to expose evolu_message.

```ts
const todoTitleHistory = (id: TodoId) =>
  evolu.createQuery((db) =>
    db
      .selectFrom("evolu_message")
      .select("value")
      .where("table", "==", "todo")
      .where("row", "==", id)
      .where("column", "==", "title")
      .$narrowType<{ value: TodoTable["title"] }>()
      .orderBy("timestamp", "desc"),
  );

evolu
  .loadQuery(todoTitleHistory("EIcGfm1Av0UFBrFd_bx69" as TodoId))
  .then(({ rows }) => {
    console.log(rows);
  });
```
